### ISSUE TITLE
compiler error using MSVC?

### ISSUE THREAD

**Issue by dmedine** [aicodix/dsp#1]
Hello. I am trying out your fft library and compiling with MSVC 142. I am running in to a templating issue
when declaring the FFT operation like this (for example):

```
DSP::FastFourierTransform< 4, double, -1>fft;
fft(pdOut, pdIn);
```

MSVC gives me a few errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2825	'TYPE': must be a class or namespace when followed by '::'	dsp\fft.hh	1116	
Error	C2510	'TYPE': left of '::' must be a class/struct/union	dsp\fft.hh	1116	
Error	C3646	'value_type': unknown override specifier	dsp\fft.hh	1116	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	dsp\fft.hh	1116	
```
I am not familiar with the syntax you use on line 1116 of fft.hh, specifically: `TYPE::type_name` where `TYPE` is the template type specifier.
. Do I need to be using clang and/or LLVM's libc++ for this to work? or am I just doing something stupid?

**Comment by dmedine** [comment]
Also, do you use the typical FFT i/o order conventions? E.g. is the input in[0] = real[0], in[1] = imag[0]... etc. and the output negative frequencies are in reverse order in the second half of the array?

**Comment by xdsopl** [comment]
You either need to use std::complex<double> or DSP::Complex<double> for the second template parameter.
And yes, the negative frequencies are in reverse order in the second half of the array.

**Comment by xdsopl** [comment]
If you still need to use an real / imag interleaved POD type array for input or output, the following might work for you:
```
typedef DSP::Complex<double> cmplx;
DSP::FastFourierTransform<4, cmplx, -1> fft;
fft(reinterpret_cast<cmplx *>(pdOut), reinterpret_cast<cmplx *>(pdIn));
```

**Comment by dmedine** [comment]
Great! This is now working perfectly. I do have another question, but it is unrelated so I close this and will open a new issue.
