### ISSUE TITLE
how to optimize DSP::FFT

### ISSUE THREAD

**Issue by dmedine** [aicodix/dsp#2]
I have done some preliminary speed tests with your DSP::FFT library against FFTW. I am sorry I cannot upload a picture here, but as the length of the FFT grows, so does the difference between the execution time of FFTW and DSP::FFT---that is to say, it grows exponentially. When nLen = 2^5, the difference is already 40 microseconds. At 2^10 it is 4 milliseconds and at 2^15 it is 129 milliseconds. Someone told me that yours is only 2x as slow as FFTW so I was surprised to see that the difference in performance time was this extreme.

Am I doing something wrong? Here is the code I use to instantiate the DSP::FFT object:
```
std::vector<DSP::Complex<double>> m_vcdDSPFFTIn,  m_vcdDSPFFTOut;
m_vcdDSPFFTIn.resize(32768);
m_vcdDSPFFTOut.resize(32768);
DSP::FastFourierTransform< 32768, DSP::Complex<double>, -1>* pFFT = new
	DSP::FastFourierTransform< 32768, DSP::Complex<double>, -1>;
```

Then I do this in a loop many times and take the average execution time:
`(*pFFT)(&m_vcdDSPFFTOut[0], &m_vcdDSPFFTIn[0]);`

Then cleanup:
`delete pFFT;`

I also tried instantiating the FFT object the more idiomatic way:
```
DSP::FastFourierTransform< 32768, DSP::Complex<double>, -1>fft;
```
and then the run looks like:
```
fft(&m_vcdDSPFFTOut[0], &m_vcdDSPFFTIn[0]);
```
But this is not ideal because when the length of the FFT >=1024 points, this exceeds Windows' stack memory and the compiler complains. Nevertheless, the code will run properly (I guess Windows works some magic back there) but the results from the speed test are basically identical.

Please let me know if I am misusing your library and if there is a way to get it running faster.

**Comment by xdsopl** [comment]
Instantiation on the heap is no problem but performance of the library heavily depends on compiler optimization flags, especially inlining.
It's usually enough to just use `-O2` with clang or gcc to get a x20 speedup over using '-O1'.

**Comment by xdsopl** [comment]
I quickly wrote a contesting benchmark to compare the double precision performance of DSP::FFT to FFTW.
https://github.com/xdsopl/contest

**Comment by dmedine** [comment]
Thanks! I fiddled with the optimization settings and got much better results, but I am still not achieving what you show here: https://github.com/xdsopl/contest. For example for an FFT length of 2^12, I get an average time of about 100 microseconds, which is the speed at which you are able to perform an FFT of length 2^13. Interestingly, my speeds for FFTW are slightly better than the plots.

Anyway, this is great. Thank you for providing this excellent DSP library to the opensource world and thanks for answering all my questions so quickly!
