### ISSUE TITLE
Help requested for resampling

### ISSUE THREAD

**Issue by LieBtrau** [aicodix/dsp#3]
Hello,

Context:
I've managed to get the next-branch of the modem running on ESP32 with 8kHz sampling rate.  The ESP32 isn't fast enough to run the modem at 48kHz.
I'd like to run the I²S-bus to the hardware codec on 48kHz.  That would make it easier to build the analog reconstruction filter that follows that the DAC.

My problem is: how I can upsample the 8kHz samples to 48kHz (following the encoder) and how to downsample 48kHz input samples to 8kHz so that I can feed them to the decoder?

I found your code on resampler.hh, but I have a hard time to understand how it works.  Here's my code to downsample 48kHz to 8kHz.  The parameters are likely all wrong, but at least it builds and runs.

I expect the code send the 48kHz samples through a 4kHz low pass filter and then keep every sixth sample.
```
void resampling()
{
    typedef float value;
    DSP::Resampler<value, 10, 3> resample(48000, 4000, 5);

    int16_t input[100];
    memset(input, 100, sizeof(input));
    int16_t output[400]={0};
    resample(output, input, 8000, 100);
    for (int i = 0; i < 400; i++)
	{
		std::cout << output[i] << " ";
	}
}
```

Would you be able to help me out with this?

**Comment by xdsopl** [comment]
The DSP::Resampler is only meant for small, fractional sample rate changes varying over time and not suited for what you are trying to do. The simplest way for you to do it is to simply output one sample from the encoder, followed by 11 zeros to the output. This will create aliasing at multiples of the original sampling rate, so a lowpass filter with a cutoff at 4kHz should be used. You could try using a simple EMA filter for that. A CIC filter would be the next optimization.

**Comment by xdsopl** [comment]
Now that I had my coffee, I see you are also asking for decimating the input. It's actually the same procedure, but reversed: you first make sure there are no frequencies beyond Nyquist by using a lowpass and then only use every sixth sample for the Hilbert transformer in the decoder. You could combine all the steps above for a much more efficient multi-phase filter to get the analytic signal while also decimating but that is an exercise left for the reader. 😉

**Comment by LieBtrau** [comment]
Hi,
Thanks for the hints.  Last weekend, I ended up using a 12-th order chebychev anti-aliasing filter.  It reconstructs my input sine wave well, but I see hick-ups in the output data.  I fear that that filter is too computationally intensive.  Time for another approach now.
